### ISSUE TITLE
Reset Password email sending incorrect URL

### ISSUE THREAD

**Issue by alexandervalencia** [wedeploy/wedeploy-sdk-js#282] opened 2019-01-24 16:15 UTC
### Environment
JavaScript SDK version: 4.5.1

Environment:
  Browser: Chrome 71.0.3578.98

### Steps to Reproduce
Send a password reset email. Here's the example from the [documentation](https://wedeploy.com/docs/auth/manage-users/#7):

```js
WeDeploy
  .auth('https://<serviceID>-<projectID>.wedeploy.io')
  .sendPasswordResetEmail("user@domain.com")
  .then(function() {
    // Email sent.
  })
  .catch(function(err) {
    // An error happened.
  });
```

### Expected Behavior

Users should receive a reset password email containing a link to allow them to reset their auth password. 

The URL should look like this: 
```html
http://<SERVICE>-<PROJECT>.wedeploy.io/reset.html?code=ZguXw1VZN6M...gTbgOLW&email=<EMAIL>@<DOMAIN>.com
```
(Parts of the link redacted for security reasons)

### Actual Behavior
A `.` is used to separate the service ID and project ID instead of a `-` resulting in a 404 page.

This is the actual link sent by email:
```html
http://<SERVICE>.<PROJECT>.wedeploy.io/reset.html?code=ZguXw1VZN6M...gTbgOLW&email=<EMAIL>@<DOMAIN>.com
```
(Parts of the link redacted for security reasons)

**Comment by ipeychev** [comment] 2019-01-25 08:58
Thanks for the report! The issue isn't in the SDK, but opened an issue where it should be.

**Comment by alexandervalencia** [comment] 2019-01-25 17:27
Thanks @ipeychev !

**Comment by alexandervalencia** [comment] 2019-01-31 00:03
@ipeychev any update on the situation?

**Comment by ipeychev** [comment] 2019-01-31 09:13
Yes, @alexandervalencia, we are working on this issue and according to @igr it will be fixed till the end of the week. Thanks again for your patience and reporting it to us!

**Comment by ipeychev** [comment] 2019-02-05 17:50
Hey @alexandervalencia, the issue was fixed. Please use `wedeploy/auth:2.8.2` in `wedeploy.json`, for example:
```
{
  "id": "auth",
  "image": "wedeploy/auth:2.8.2"
}
```

Thanks for your patience!

Sincerely,
WeDeploy Team

**Closed by ipeychev** 2019-02-05 17:50 UTC

**Comment by alexandervalencia** [comment] 2019-02-08 23:38
Thanks for the fix!
